# syntax=docker/dockerfile:1
# Dockerfile for FedScale Aggregator

FROM yilegu/fedscale-base:v1.0

WORKDIR /FedScale

# COPY all source files execept ignored by .dockerignore
COPY . .

RUN /bin/bash -c 'chmod +x ./docker/run-aggr.sh'

# Config PATH
ENV PATH="${PATH}:/root/anaconda3/bin:/root/anaconda3/condabin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# Run Aggregator
CMD ["/bin/bash", "-c", "./docker/run-aggr.sh"]
